In [2]:
import torch

In [18]:
xs = torch.linspace(0.01, 1, 1000)
xs

tensor([0.0100, 0.0110, 0.0120, 0.0130, 0.0140, 0.0150, 0.0159, 0.0169, 0.0179,
        0.0189, 0.0199, 0.0209, 0.0219, 0.0229, 0.0239, 0.0249, 0.0259, 0.0268,
        0.0278, 0.0288, 0.0298, 0.0308, 0.0318, 0.0328, 0.0338, 0.0348, 0.0358,
        0.0368, 0.0377, 0.0387, 0.0397, 0.0407, 0.0417, 0.0427, 0.0437, 0.0447,
        0.0457, 0.0467, 0.0477, 0.0486, 0.0496, 0.0506, 0.0516, 0.0526, 0.0536,
        0.0546, 0.0556, 0.0566, 0.0576, 0.0586, 0.0595, 0.0605, 0.0615, 0.0625,
        0.0635, 0.0645, 0.0655, 0.0665, 0.0675, 0.0685, 0.0695, 0.0705, 0.0714,
        0.0724, 0.0734, 0.0744, 0.0754, 0.0764, 0.0774, 0.0784, 0.0794, 0.0804,
        0.0814, 0.0823, 0.0833, 0.0843, 0.0853, 0.0863, 0.0873, 0.0883, 0.0893,
        0.0903, 0.0913, 0.0923, 0.0932, 0.0942, 0.0952, 0.0962, 0.0972, 0.0982,
        0.0992, 0.1002, 0.1012, 0.1022, 0.1032, 0.1041, 0.1051, 0.1061, 0.1071,
        0.1081, 0.1091, 0.1101, 0.1111, 0.1121, 0.1131, 0.1141, 0.1150, 0.1160,
        0.1170, 0.1180, 0.1190, 0.1200, 

In [19]:
xs.prod()

tensor(0.)

In [20]:
xs = torch.linspace(0.01, 1, 100)
xs.prod()

tensor(9.3326e-43)

In [23]:
xs = torch.linspace(0.01, 1, 1000)
a = xs.log().sum()

b = torch.linspace(0.01, 1, 10000).log().sum()
print(a, b)

tensor(-954.8404) tensor(-9536.1816)


In [6]:
torch.linspace(0.01, 1, 1000).log().sum()

tensor(-954.8404)

In [7]:
torch.linspace(0.01, 1, 10000).log().sum()

tensor(-9536.1816)

In [8]:
# Trivial example to test the binary cross entropy loss

y_true = torch.tensor([0., 1., 1., 0.])
logits = torch.tensor([0.1, 0.9, 0.8, 0.2])

loss = torch.nn.BCEWithLogitsLoss()
loss(logits, y_true)

tensor(0.5637)

In [9]:

y_hat = torch.nn.Sigmoid()(logits)
y_hat

tensor([0.5250, 0.7109, 0.6900, 0.5498])

In [10]:
# BCE
-(y_true * torch.log(y_hat) + (1 - y_true) * torch.log(1 - y_hat)).mean()

tensor(0.5637)

In [11]:
def our_bce(y_true, logits):
    y_hat = torch.nn.Sigmoid()(logits)
    return -(y_true * torch.log(y_hat) + (1 - y_true) * torch.log(1 - y_hat)).mean()

In [12]:
# check that our implementation is correct
assert our_bce(y_true, logits) == loss(logits, y_true)


In [13]:
# Larger logits
logits = torch.tensor([100., 200., 300., 400.])

assert our_bce(y_true, logits) == loss(logits, y_true)



AssertionError: 

In [14]:
torch.nn.Sigmoid()(logits)

tensor([1., 1., 1., 1.])

In [15]:
torch.exp(logits)/(1 + torch.exp(logits))

tensor([nan, nan, nan, nan])

In [16]:
torch.exp(-logits)

tensor([3.7835e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00])

In [17]:
1/(1+torch.exp(-logits))

tensor([1., 1., 1., 1.])