In [1]:
import pandas as pd
import numpy as np
import jax.numpy as jnp
import jax

In [2]:
def func(x, y, z):
    return x**2 + jnp.sin(y) + z


In [3]:
func(1, 2, 3)

DeviceArray(4.9092975, dtype=float32, weak_type=True)

In [4]:
from sympy import *
init_printing()

x, y, z = symbols('x y z')
f = x**2 + sin(y) + z
f

In [20]:
diff(f, x)

In [11]:
# Find the derivative of f with respect to x, y, and z using sympy
del_x, del_y, del_z = diff(f, x), diff(f, y), diff(f, z)
del_x, del_y, del_z

In [21]:
grad_f = lambdify((x, y, z), [del_x, del_y, del_z])
grad_f(1, 2, 3)

In [29]:
grad_f_jax = jax.grad(func, argnums=(0, 1, 2))
grad_f_jax(1., 2., 3.)

(DeviceArray(2., dtype=float32, weak_type=True),
 DeviceArray(-0.41614684, dtype=float32, weak_type=True),
 DeviceArray(1., dtype=float32, weak_type=True))

In [92]:
n = 20
A = jax.random.normal(shape=(1, n), key=jax.random.PRNGKey(0), dtype=jnp.float32)
theta = jax.random.normal(shape=(n, 1), key=jax.random.PRNGKey(0), dtype=jnp.float32)
b = A @ theta 

b

DeviceArray([[28.684494]], dtype=float32)

In [93]:
b.flatten(), b.item()

(DeviceArray([28.684494], dtype=float32), 28.684494018554688)

In [94]:
def a_theta(A, theta):
    return A @ theta

In [95]:
a_theta(A, theta)

DeviceArray([[28.684494]], dtype=float32)

In [96]:
grad_a_theta = jax.grad(a_theta, argnums=1)

In [101]:
jax.jacobian(a_theta, argnums=1)(A, theta)[0, 0, :].shape

In [102]:
A.shape

In [112]:
# Sympy version

In [109]:
A = MatrixSymbol('A', 1, n)
theta = MatrixSymbol('theta', n, 1)
A, theta

In [111]:
diff(A*theta, theta)